import ProfileNav from "@/components/Navbar/ProfileNav";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const backgroundImage = {
  backgroundImage: 'url("/creatorProfileBg.png")', // Ensure the correct path
  backgroundSize: "cover",
  backgroundRepeat: 'no-repeat',
  backgroundPosition: 'center',
  width: '100%',
  height: '100vh',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Static metadata for page when it's opened */}
        <title>CreatorX</title>
        <meta name="description" content="Generated by e-8 Labs" />
        <link rel="icon" href="/creaatorXlogomain.png" />

        {/* Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <div className="flex flex-row w-full" style={backgroundImage}>
          <div className="w-2/12 h-screen">
            <ProfileNav />
          </div>
          <div className="w-10/12">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
