import ProfileNav from "@/components/Navbar/ProfileNav";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// Static metadata for when users are browsing the site
export const metadata = {
  title: "CreatorX",
  description: "Generated by e-8 Labs",
};

const backgroundImage = {
  backgroundImage: 'url("/creatorProfileBg.png")', // Ensure the correct path
  backgroundSize: "cover",
  backgroundRepeat: 'no-repeat',
  backgroundPosition: 'center',
  width: '100%',
  height: '100vh',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Static favicon and title for users browsing the site */}
        <title>CreatorX</title> 
        <meta title="CreatorX" description="Generated by e-8 Labs" />
        <metadata title="CreatorX" description="Generated by e-8 Labs" />
        <link rel="icon" href="/creaatorXlogomain.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <div className="flex flex-row w-full" style={backgroundImage}>
          <div className="w-2/12 h-screen">
            <ProfileNav />
          </div>
          <div className="w-10/12">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
