// import ProfileNav from "@/components/Navbar/ProfileNav";
// import CallerProfileNav from "@/creatorProfileComponents/callerProfileNav/CallerProfileNav";
// import CallerMenu from "@/components/Navbar/callerProfileNavComponents/CallerMenu";
import CallerMenu from "@/components/Navbar/CallerMenu";
import CallerProfileNav from "@/components/Navbar/callerProfileNavComponents/CallerProfileNav";
// import CallerProfileNav from "@/components/Navbar/callerProfileNavComponents/CallerProfileNav";
import { Drawer } from "@mui/material";
import { Inter } from "next/font/google";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Voice.ai",
    description: "Generated by E-8 labs",
};

const backgroundImage = {
    backgroundImage: 'url("/creatorProfileBg.png")', // Ensure the correct path
    backgroundSize: "cover",
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center',
    width: '100%',
    height: '100vh',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            {/* <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet" />
            </head> flex-col lg:flex-row*/}
            <body className={inter.className}>
                <div className="flex flex-row w-full" style={backgroundImage}>
                    <div className="lg:flex hidden w-2/12 h-screen">
                        {/* <CallerProfileNav /> */}
                        <CallerProfileNav />
                    </div>
                    <div className="lg:hidden" style={{ backgroundColor: "#ffffff30" }}>
                        <div>
                            <CallerMenu />
                        </div>
                    </div>
                    <div className="lg:w-10/12 w-full">
                        {children}
                    </div>
                    
                </div>
            </body>
        </html>
    );
}