// import ProfileNav from "@/components/Navbar/ProfileNav";
// import CallerProfileNav from "@/creatorProfileComponents/callerProfileNav/CallerProfileNav";
import CallerProfileNav from "@/components/Navbar/callerProfileNavComponents/CallerProfileNav";
import { Inter } from "next/font/google";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const backgroundImage = {
    backgroundImage: 'url("/creatorProfileBg.png")', // Ensure the correct path
    backgroundSize: "cover",
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center',
    width: '100%',
    height: '100vh',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            {/* <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet" />
            </head> */}
            <body className={inter.className}>
                <div className="flex flex-row w-full" style={backgroundImage}>
                    <div className="w-2/12 h-screen">
                        {/* <CallerProfileNav /> */}
                        <CallerProfileNav />
                    </div>
                    <div className="w-10/12">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}